-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 15, 2022 at 12:21 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `infinite_scrolling`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `post` text NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `post`, `date`) VALUES
(202, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Multoque hoc melius nos veriusque quam Stoici. Non est igitur voluptas bonum. Quonam modo? </p>\n\n<p>Quae diligentissime contra Aristonem dicuntur a Chryippo. Quae cum dixisset paulumque institisset, Quid est? </p>\n\n<p>Duo Reges: constructio interrete. Videmus igitur ut conquiescere ne infantes quidem possint. Illa tamen simplicia, vestra versuta. Videmus igitur ut conquiescere ne infantes quidem possint. Sin aliud quid voles, postea. Nunc agendum est subtilius. Cur igitur, inquam, res tam dissimiles eodem nomine appellas? Conclusum est enim contra Cyrenaicos satis acute, nihil ad Epicurum. </p>\n\n', '2022-04-14 19:19:58'),
(203, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ita multa dicunt, quae vix intellegam. Murenam te accusante defenderem. Quibus ego vehementer assentior. Duo Reges: constructio interrete. Si id dicis, vicimus. Quare conare, quaeso. Tria genera bonorum; </p>\n\n<p>Et quidem, inquit, vehementer errat; Immo videri fortasse. De quibus cupio scire quid sentias. Restinguet citius, si ardentem acceperit. Restatis igitur vos; Sedulo, inquam, faciam. </p>\n\n<p>Si longus, levis; Torquatus, is qui consul cum Cn. Non autem hoc: igitur ne illud quidem. Tollenda est atque extrahenda radicitus. Quae sequuntur igitur? </p>\n\n', '2022-04-14 19:19:58'),
(204, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Videamus animi partes, quarum est conspectus illustrior; Bonum incolumis acies: misera caecitas. Sed videbimus. </p>\n\n<p>Gerendus est mos, modo recte sentiat. Sed ille, ut dixi, vitiose. Duo Reges: constructio interrete. Quamquam tu hanc copiosiorem etiam soles dicere. Sed tamen intellego quid velit. </p>\n\n<p>Sic consequentibus vestris sublatis prima tolluntur. Negare non possum. Nescio quo modo praetervolavit oratio. Mihi enim satis est, ipsis non satis. At enim hic etiam dolore. Sedulo, inquam, faciam. </p>\n\n', '2022-04-14 19:19:59'),
(205, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Erat enim Polemonis. Sullae consulatum? Non quam nostram quidem, inquit Pomponius iocans; Quamquam id quidem licebit iis existimare, qui legerint. Nos commodius agimus. </p>\n\n<p>Duo Reges: constructio interrete. Summae mihi videtur inscitiae. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; At ego quem huic anteponam non audeo dicere; De vacuitate doloris eadem sententia erit. Ita nemo beato beatior. Haec para/doca illi, nos admirabilia dicamus. Quid enim? </p>\n\n<p>An eiusdem modi? Cur iustitia laudatur? Quae sequuntur igitur? Easdemne res? </p>\n\n', '2022-04-14 19:20:00'),
(206, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque fecimus. Quo modo autem philosophus loquitur? Duo Reges: constructio interrete. Non semper, inquam; Quorum altera prosunt, nocent altera. Itaque hic ipse iam pridem est reiectus; </p>\n\n<p>Quae cum dixisset paulumque institisset, Quid est? Omnia contraria, quos etiam insanos esse vultis. Quis enim redargueret? Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; </p>\n\n<p>Et quidem, inquit, vehementer errat; Nunc haec primum fortasse audientis servire debemus. Quod totum contra est. An haec ab eo non dicuntur? Iam contemni non poteris. Sint ista Graecorum; At eum nihili facit; </p>\n\n', '2022-04-14 19:20:00'),
(207, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc omni virtuti vitium contrario nomine opponitur. Ego vero volo in virtute vim esse quam maximam; </p>\n\n<p>Sed ille, ut dixi, vitiose. Duo Reges: constructio interrete. Est enim effectrix multarum et magnarum voluptatum. Primum in nostrane potestate est, quid meminerimus? At, si voluptas esset bonum, desideraret. </p>\n\n<p>Tubulo putas dicere? Graece donan, Latine voluptatem vocant. Bonum valitudo: miser morbus. </p>\n\n', '2022-04-14 19:20:01'),
(208, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Istam voluptatem perpetuam quis potest praestare sapienti? Nunc haec primum fortasse audientis servire debemus. Suo genere perveniant ad extremum; Duo Reges: constructio interrete. At hoc in eo M. Itaque fecimus. </p>\n\n<p>Nihil illinc huc pervenit. Ad eos igitur converte te, quaeso. Qua tu etiam inprudens utebare non numquam. An vero, inquit, quisquam potest probare, quod perceptfum, quod. Primum in nostrane potestate est, quid meminerimus? Itaque his sapiens semper vacabit. </p>\n\n<p>Tum Quintus: Est plane, Piso, ut dicis, inquit. Sic enim censent, oportunitatis esse beate vivere. Inde sermone vario sex illa a Dipylo stadia confecimus. Tu vero, inquam, ducas licet, si sequetur; </p>\n\n', '2022-04-14 19:20:01'),
(209, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ad rem redeamus; Non est igitur voluptas bonum. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Quae contraria sunt his, malane? Scisse enim te quis coarguere possit? </p>\n\n<p>Duo enim genera quae erant, fecit tria. Paria sunt igitur. Cyrenaici quidem non recusant; An tu me de L. Etiam beatissimum? Tollenda est atque extrahenda radicitus. </p>\n\n<p>Duo Reges: constructio interrete. Sed haec nihil sane ad rem; </p>\n\n', '2022-04-14 19:20:02'),
(210, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non quam nostram quidem, inquit Pomponius iocans; Duo Reges: constructio interrete. Negat enim summo bono afferre incrementum diem. Immo alio genere; Tum Torquatus: Prorsus, inquit, assentior; </p>\n\n<p>Quis hoc dicit? Quo studio Aristophanem putamus aetatem in litteris duxisse? </p>\n\n<p>Nam quid possumus facere melius? Et nemo nimium beatus est; In schola desinis. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Non igitur bene. Quid ad utilitatem tantae pecuniae? Eaedem enim utilitates poterunt eas labefactare atque pervertere. </p>\n\n', '2022-04-14 19:20:02'),
(211, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed haec omittamus; Est, ut dicis, inquam. </p>\n\n<p>Cui Tubuli nomen odio non est? Certe, nisi voluptatem tanti aestimaretis. Duo Reges: constructio interrete. Haec dicuntur inconstantissime. Praeteritis, inquit, gaudeo. Conferam tecum, quam cuique verso rem subicias; Satis est ad hoc responsum. </p>\n\n<p>Beatus sibi videtur esse moriens. Comprehensum, quod cognitum non habet? </p>\n\n', '2022-04-14 19:20:03'),
(212, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Minime vero istorum quidem, inquit. Tubulo putas dicere? Stoicos roga. </p>\n\n<p>Duo Reges: constructio interrete. Videsne quam sit magna dissensio? Sed tamen intellego quid velit. Utram tandem linguam nescio? </p>\n\n<p>Tum Torquatus: Prorsus, inquit, assentior; Bonum valitudo: miser morbus. Idemne, quod iucunde? An hoc usque quaque, aliter in vita? Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; Ergo illi intellegunt quid Epicurus dicat, ego non intellego? Quid iudicant sensus? </p>\n\n', '2022-04-14 19:20:03'),
(213, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non laboro, inquit, de nomine. Quid de Platone aut de Democrito loquar? Dici enim nihil potest verius. De quibus cupio scire quid sentias. </p>\n\n<p>Ita prorsus, inquam; Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Ne discipulum abducam, times. At multis malis affectus. </p>\n\n<p>Ad eos igitur converte te, quaeso. Ut pulsi recurrant? Inscite autem medicinae et gubernationis ultimum cum ultimo sapientiae comparatur. At, si voluptas esset bonum, desideraret. </p>\n\n', '2022-04-14 19:20:04'),
(214, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Peccata paria. Quid enim possumus hoc agere divinius? Sed haec omittamus; Nonne igitur tibi videntur, inquit, mala? Vide, quaeso, rectumne sit. </p>\n\n<p>Paria sunt igitur. Bonum incolumis acies: misera caecitas. Quis Aristidem non mortuum diligit? Hoc tu nunc in illo probas. </p>\n\n<p>Duo Reges: constructio interrete. Tum ille: Ain tandem? Graece donan, Latine voluptatem vocant. Gloriosa ostentatio in constituendo summo bono. </p>\n\n', '2022-04-14 19:20:04'),
(215, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Honesta oratio, Socratica, Platonis etiam. Atqui reperies, inquit, in hoc quidem pertinacem; Quid vero? Cur post Tarentum ad Archytam? Duo Reges: constructio interrete. </p>\n\n<p>Quia nec honesto quic quam honestius nec turpi turpius. Primum in nostrane potestate est, quid meminerimus? Non risu potius quam oratione eiciendum? Nunc agendum est subtilius. Si quae forte-possumus. Efficiens dici potest. Igitur ne dolorem quidem. Immo alio genere; </p>\n\n<p>Istam voluptatem, inquit, Epicurus ignorat? Quod quidem iam fit etiam in Academia. Videsne quam sit magna dissensio? Dat enim intervalla et relaxat. Sed potestne rerum maior esse dissensio? Habent enim et bene longam et satis litigiosam disputationem. Summae mihi videtur inscitiae. </p>\n\n', '2022-04-14 19:20:04'),
(216, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mehercule pergrata mihi oratio tua. Quid iudicant sensus? Quonam, inquit, modo? Quae diligentissime contra Aristonem dicuntur a Chryippo. Quis enim redargueret? Contineo me ab exemplis. Duo Reges: constructio interrete. </p>\n\n<p>Quid ergo attinet gloriose loqui, nisi constanter loquare? Suo genere perveniant ad extremum; Tu vero, inquam, ducas licet, si sequetur; Nam quid possumus facere melius? Eam stabilem appellas. </p>\n\n<p>Hunc vos beatum; Ut pulsi recurrant? </p>\n\n', '2022-04-14 19:20:05'),
(217, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Deprehensus omnem poenam contemnet. Quippe: habes enim a rhetoribus; Sint modo partes vitae beatae. Estne, quaeso, inquam, sitienti in bibendo voluptas? Scio enim esse quosdam, qui quavis lingua philosophari possint; At enim hic etiam dolore. Duo Reges: constructio interrete. Sed hoc sane concedamus. </p>\n\n<p>Tria genera bonorum; Praeclare hoc quidem. Inde igitur, inquit, ordiendum est. An nisi populari fama? De illis, cum volemus. At ego quem huic anteponam non audeo dicere; </p>\n\n<p>Ille enim occurrentia nescio quae comminiscebatur; Quid ad utilitatem tantae pecuniae? Quid Zeno? Tu vero, inquam, ducas licet, si sequetur; Itaque contra est, ac dicitis; Idemque diviserunt naturam hominis in animum et corpus. </p>\n\n', '2022-04-14 19:20:05'),
(218, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tollenda est atque extrahenda radicitus. Age, inquies, ista parva sunt. </p>\n\n<p>Dici enim nihil potest verius. Nos commodius agimus. Quid dubitas igitur mutare principia naturae? Restatis igitur vos; </p>\n\n<p>Recte dicis; Duo Reges: constructio interrete. Praeclare hoc quidem. </p>\n\n', '2022-04-14 19:20:06'),
(219, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Restinguet citius, si ardentem acceperit. Idem adhuc; Aeque enim contingit omnibus fidibus, ut incontentae sint. Nam de isto magna dissensio est. Omnes enim iucundum motum, quo sensus hilaretur. Duo Reges: constructio interrete. </p>\n\n<p>Quid ergo? Eam stabilem appellas. Sit sane ista voluptas. Satis est ad hoc responsum. </p>\n\n<p>Sed mehercule pergrata mihi oratio tua. Non laboro, inquit, de nomine. Tamen a proposito, inquam, aberramus. Equidem e Cn. Nihilo magis. </p>\n\n', '2022-04-14 19:20:06'),
(220, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nos commodius agimus. Num quid tale Democritus? Gloriosa ostentatio in constituendo summo bono. Summum a vobis bonum voluptas dicitur. Duo Reges: constructio interrete. Tuo vero id quidem, inquam, arbitratu. Equidem e Cn. </p>\n\n<p>Sed ego in hoc resisto; Qua igitur re ab deo vincitur, si aeternitate non vincitur? Quis Aristidem non mortuum diligit? Respondeat totidem verbis. Sed quid attinet de rebus tam apertis plura requirere? </p>\n\n<p>Ergo id est convenienter naturae vivere, a natura discedere. Eiuro, inquit adridens, iniquum, hac quidem de re; </p>\n\n', '2022-04-14 19:20:07'),
(221, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod quidem iam fit etiam in Academia. Quam illa ardentis amores excitaret sui! Cur tandem? Duo Reges: constructio interrete. Dat enim intervalla et relaxat. Quantum Aristoxeni ingenium consumptum videmus in musicis? Quae similitudo in genere etiam humano apparet. </p>\n\n<p>Unum est sine dolore esse, alterum cum voluptate. Summum ením bonum exposuit vacuitatem doloris; </p>\n\n<p>Quis istum dolorem timet? Prioris generis est docilitas, memoria; Eaedem res maneant alio modo. Poterat autem inpune; </p>\n\n', '2022-04-14 19:20:07'),
(222, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ne discipulum abducam, times. Sed in rebus apertissimis nimium longi sumus. Non semper, inquam; Duo Reges: constructio interrete. Videsne quam sit magna dissensio? Oratio me istius philosophi non offendit; </p>\n\n<p>Tu vero, inquam, ducas licet, si sequetur; Quam ob rem tandem, inquit, non satisfacit? Duo enim genera quae erant, fecit tria. Quid adiuvas? </p>\n\n<p>Laboro autem non sine causa; Sit enim idem caecus, debilis. Quid dubitas igitur mutare principia naturae? Itaque fecimus. Age, inquies, ista parva sunt. </p>\n\n', '2022-04-14 19:20:08'),
(223, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc tu nunc in illo probas. Putabam equidem satis, inquit, me dixisse. Esse enim, nisi eris, non potes. Sed quot homines, tot sententiae; Non est igitur summum malum dolor. </p>\n\n<p>Honesta oratio, Socratica, Platonis etiam. Duo Reges: constructio interrete. </p>\n\n<p>Bonum integritas corporis: misera debilitas. Equidem, sed audistine modo de Carneade? Hoc non est positum in nostra actione. De quibus cupio scire quid sentias. </p>\n\n', '2022-04-14 19:20:08'),
(224, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc sic expositum dissimile est superiori. Duo Reges: constructio interrete. Primum divisit ineleganter; Cur post Tarentum ad Archytam? Mihi enim satis est, ipsis non satis. Ut proverbia non nulla veriora sint quam vestra dogmata. </p>\n\n<p>Quae contraria sunt his, malane? Maximus dolor, inquit, brevis est. </p>\n\n<p>Hoc ipsum elegantius poni meliusque potuit. Comprehensum, quod cognitum non habet? Haec quo modo conveniant, non sane intellego. Respondent extrema primis, media utrisque, omnia omnibus. Quod iam a me expectare noli. Efficiens dici potest. Quid sequatur, quid repugnet, vident. </p>\n\n', '2022-04-14 19:20:08'),
(225, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ego in hoc resisto; Sed haec nihil sane ad rem; Tuo vero id quidem, inquam, arbitratu. Tuo vero id quidem, inquam, arbitratu. Eadem nunc mea adversum te oratio est. </p>\n\n<p>Duo Reges: constructio interrete. Quippe: habes enim a rhetoribus; Tum Quintus: Est plane, Piso, ut dicis, inquit. Ea possunt paria non esse. Tum Quintus: Est plane, Piso, ut dicis, inquit. Profectus in exilium Tubulus statim nec respondere ausus; </p>\n\n<p>Nulla erit controversia. Quare conare, quaeso. Eam stabilem appellas. Sin aliud quid voles, postea. Quae quidem vel cum periculo est quaerenda vobis; Hoc Hieronymus summum bonum esse dixit. </p>\n\n', '2022-04-14 19:20:09'),
(226, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque hic ipse iam pridem est reiectus; Igitur neque stultorum quisquam beatus neque sapientium non beatus. Minime vero, inquit ille, consentit. Hoc sic expositum dissimile est superiori. Duo Reges: constructio interrete. Estne, quaeso, inquam, sitienti in bibendo voluptas? </p>\n\n<p>Huius, Lyco, oratione locuples, rebus ipsis ielunior. At enim sequor utilitatem. Itaque hic ipse iam pridem est reiectus; Ratio quidem vestra sic cogit. Ut aliquid scire se gaudeant? Nos cum te, M. Invidiosum nomen est, infame, suspectum. </p>\n\n<p>Tum Quintus: Est plane, Piso, ut dicis, inquit. Nos vero, inquit ille; Nullus est igitur cuiusquam dies natalis. Nunc haec primum fortasse audientis servire debemus. Ego vero isti, inquam, permitto. </p>\n\n', '2022-04-14 19:20:09'),
(227, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nobis aliter videtur, recte secusne, postea; Non est igitur voluptas bonum. Non semper, inquam; Nos vero, inquit ille; Sed quot homines, tot sententiae; Ad eas enim res ab Epicuro praecepta dantur. Duo Reges: constructio interrete. Refert tamen, quo modo. </p>\n\n<p>Nam quid possumus facere melius? Quae sequuntur igitur? Stoici scilicet. Ita fit cum gravior, tum etiam splendidior oratio. </p>\n\n<p>Quae cum dixisset, finem ille. At hoc in eo M. Certe, nisi voluptatem tanti aestimaretis. Contemnit enim disserendi elegantiam, confuse loquitur. Quare conare, quaeso. </p>\n\n', '2022-04-14 19:20:10'),
(228, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis enim redargueret? Illi enim inter se dissentiunt. Summus dolor plures dies manere non potest? Recte, inquit, intellegis. Duo Reges: constructio interrete. Inde igitur, inquit, ordiendum est. </p>\n\n<p>Quis non odit sordidos, vanos, leves, futtiles? Quis est, qui non oderit libidinosam, protervam adolescentiam? Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. Poterat autem inpune; Nonne videmus quanta perturbatio rerum omnium consequatur, quanta confusio? Certe nihil nisi quod possit ipsum propter se iure laudari. </p>\n\n<p>Sed mehercule pergrata mihi oratio tua. Sit enim idem caecus, debilis. Memini vero, inquam; Nos commodius agimus. </p>\n\n', '2022-04-14 19:20:10'),
(229, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Sed in rebus apertissimis nimium longi sumus. Qualem igitur hominem natura inchoavit? Non semper, inquam; Duo Reges: constructio interrete. Quid ad utilitatem tantae pecuniae? In schola desinis. </p>\n\n<p>Quare conare, quaeso. Eaedem res maneant alio modo. Nihilo magis. Utilitatis causa amicitia est quaesita. An nisi populari fama? Id mihi magnum videtur. </p>\n\n<p>Unum est sine dolore esse, alterum cum voluptate. Videmus igitur ut conquiescere ne infantes quidem possint. Nemo igitur esse beatus potest. Prave, nequiter, turpiter cenabat; </p>\n\n', '2022-04-14 19:20:11'),
(230, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. An eiusdem modi? Hoc tu nunc in illo probas. Deprehensus omnem poenam contemnet. Negat enim summo bono afferre incrementum diem. </p>\n\n<p>Occultum facinus esse potuerit, gaudebit; Re mihi non aeque satisfacit, et quidem locis pluribus. Quae diligentissime contra Aristonem dicuntur a Chryippo. Nemo igitur esse beatus potest. Quamvis enim depravatae non sint, pravae tamen esse possunt. </p>\n\n<p>Duo Reges: constructio interrete. Idemne, quod iucunde? Immo videri fortasse. Ostendit pedes et pectus. Quid de Pythagora? Falli igitur possumus. Solum praeterea formosum, solum liberum, solum civem, stultost; Illa argumenta propria videamus, cur omnia sint paria peccata. </p>\n\n', '2022-04-14 19:20:11'),
(231, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ne, dum huic obsequor, vobis molestus sim. Sed plane dicit quod intellegit. Non est igitur voluptas bonum. Cur iustitia laudatur? Duo Reges: constructio interrete. </p>\n\n<p>Facete M. Et nemo nimium beatus est; Certe, nisi voluptatem tanti aestimaretis. Videsne, ut haec concinant? Peccata paria. Equidem etiam Epicurum, in physicis quidem, Democriteum puto. </p>\n\n<p>Summum a vobis bonum voluptas dicitur. Quae contraria sunt his, malane? Quid adiuvas? Et nemo nimium beatus est; Primum in nostrane potestate est, quid meminerimus? </p>\n\n', '2022-04-14 19:20:11');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=232;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
